core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.main_view,name='main'),
    path('logout/',views.logout_view,name='logout'),
    path('add-task/',views.add_task_view,name='add-task'),
    path('succsess/',views.succsess_tasks_view,name='succsess-tasks'),
    path('archived/',views.archived_tasks_view,name='archived-tasks'),
    path('overdue/',views.overdue_tasks_view,name='overdue-tasks'),
    path('change/<int:id>',views.change_task_view,name='change'),
]

custom/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
]

to_do_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('core.urls')),
    path('',include('custom.urls')),
    path('admin/', admin.site.urls)
]

core/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

class Task(models.Model):
    STATUS_CHOICES = [
        ('Pending','pending'),
        ('Archived','archived'),
        ('Sucsess','sucsess')
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="tasks")
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField()
    status = models.CharField(choices=STATUS_CHOICES,default='pending',max_length=8)

custom/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

core/views.py
from time import strptime
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import decorators,logout
from django.contrib import messages
from django.conf import settings
from .models import Task
from datetime import datetime

    
def logout_view(request):
    if request.user is not None:
        logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

@decorators.login_required()
def main_view(request):
    if request.method=="GET":
        tasks = Task.objects.filter(user=request.user,status='pending',date__gte=datetime.now()).order_by('date')
        return render(request,'html/main.html',{'tasks':tasks,'view':'main'})

@decorators.login_required()
def succsess_tasks_view(request):
    if request.method=="GET":
        tasks = Task.objects.filter(user=request.user,status='sucsess').order_by('date')
        return render(request,'html/main.html',{'tasks':tasks,'view':'succsess-tasks'})

@decorators.login_required()   
def archived_tasks_view(request):
    if request.method=="GET":
        tasks = Task.objects.filter(user=request.user,status='archived').order_by('date')
        return render(request,'html/main.html',{'tasks':tasks,'view':'archived-tasks'})

@decorators.login_required()
def overdue_tasks_view(request):
    if request.method=="GET":
        tasks = Task.objects.filter(user=request.user,status='pending',date__lte=datetime.now()).order_by('date')
        return render(request,'html/main.html',{'tasks':tasks,'view':'overdue-tasks'})

@decorators.login_required()
def change_task_view(request,id):
    if request.method == 'POST':
        action = request.POST.get('action')
        print(action)
        task = get_object_or_404(Task,id=id)
        action , view = action.split('-!-')
        if action == 'delete':
            task.delete()
            messages.success(request,'task deleted sucessfully')

        elif action == 'archive':
            task.status = 'archived'
            task.save()
            messages.success(request,'task archived sucessfully')

        elif action == 'sucsess':
            task.status = 'sucsess'
            task.save()
            messages.success(request,'task combleted sucessfully')

        return redirect(f'core:{view}')
    return redirect('core:main')

@decorators.login_required()
def add_task_view(request):
    
    if request.method == "GET":
        return render(request,"html/add_task.html")
    if request.method == "POST":
        title = request.POST.get("title").lstrip()
        body = request.POST.get("body").lstrip()
        date = request.POST.get("date")
        now = datetime.now()

        try:
            date = strptime(date,f"%Y-%m-%dT%H:%M")
            date = datetime(date.tm_year,date.tm_mon,date.tm_mday,date.tm_hour,date.tm_min)

            if body == '' or title == '' or date == '':
                messages.error(request,'please enter all the data')

            elif now > date:
                messages.error(request,'task date must be at the present')

            else:
                Task.objects.create(user=request.user,title=title,body=body,date=date)   
                messages.success(request,'Task added successfully')
        
        except ValueError:
            messages.error(request,'time format error , year must be less than 9999')
  
        return render(request,'html/add_task.html')
    

custom/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.conf import settings
from .models import User

def signup_view(request):
    if request.method == "GET":
        return render(request,'html/sigup.html')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        try:
            User.objects.get(username=username)
            messages.error(request,'username already used')
        except User.DoesNotExist:
            user = User.objects.create(username=username)
            user.set_password(password)
            user.save()
            login(request,user)
            return redirect(settings.LOGIN_REDIRECT_URL)
        return redirect('auth:signup')

def login_view(request):
    if request.method == "GET":
        return render(request,'html/login.html')
    if request.method =="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect(settings.LOGIN_REDIRECT_URL)
        messages.error(request,'Invalid credentials')
        return render(request,'html/login.html')

core/templates/html/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add task</title>

    <style>
        body {
            background-color: blanchedalmond;
        }
        a{
            font-size: 20px;
            color: black;
            font-weight: bolder;
            text-decoration: none;
        }
        .custom_form{
            left      : 50%;
            top       : 50%;
            position  : absolute;
            transform : translate(-50%, -50%);
            text-align: center;
            background-color: pink;
            min-height: 20%;
            min-width: 20%;
            padding: 10px;
        }
        .suc {
            text-align: center;
            font-size: large;
            font-weight: bold;
            color: red;
        }
        .banner {
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            padding: 10px;
            background-color: pink;
        }
    </style>
    
</head>
<body>
    <div class="banner">
        <a href="{% url 'core:main' %}">{{request.user.username}}</a>
        <a href="{% url 'core:add-task' %}">add task</a>
        <a href="{% url 'core:succsess-tasks' %}">sucsses tasks</a>
        <a href="{% url 'core:archived-tasks' %}">archived tasks</a>
        <a href="{% url 'core:overdue-tasks' %}">overdue tasks</a>
        <a href="{% url 'core:logout' %}">logout</a>
    </div>

    <div class="custom_form styling">
        {% if messages %}
            {% for message in messages %}
            <p class="suc" >{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form action="{% url 'core:add-task' %}" method="post">
            {% csrf_token %}
            <input type="text" name="title" placeholder="title"><br><br>
            <textarea name="body" style="resize:none" cols="50" rows="10" placeholder="body"></textarea><br><br>
            <input type="datetime-local" name="date" placeholder="date"><br><br>
            <input type="submit">
        </form>
    </div>
</body>
</html>

core/templates/html/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>to do app</title>
    
    <style>
        body {
            background-color: blanchedalmond;
        }
        .banner {
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            padding: 10px;
            background-color: pink;
            margin-bottom: 10px;
        }
        a{
            font-size: 20px;
            color: black;
            font-weight: bolder;
            text-decoration: none;
        }
        .tsk {
            padding: 10px 20px;
            margin: 5px;
            background-color: whitesmoke;
        }
        .detail {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        .detail form {
            min-width: fit-content;
        }
        form button {
            width: 100px;
            color: whitesmoke;
            padding: 10px;
            flex-shrink: 0;
        }
        .center{
                left      : 50%;
                top       : 50%;
                position  : absolute;
                transform : translate(-50%, -50%);
                text-align: center;
            }
    </style>

</head>
<body>
    <div class="banner">
        <a href="{% url 'core:main' %}">{{request.user.username}}</a>
        <a href="{% url 'core:add-task' %}">add task</a>
        <a href="{% url 'core:succsess-tasks' %}">sucsses tasks</a>
        <a href="{% url 'core:archived-tasks' %}">archived tasks</a>
        <a href="{% url 'core:overdue-tasks' %}">overdue tasks</a>
        <a href="{% url 'core:logout' %}">logout</a>
    </div>

    {% for message in messages %}
    <div style="text-align: center;" class="tsk">
        <h3 style="color: lime;">{{message}}</h3>
    </div>
    {% endfor %}

    {% for task in tasks %}
        <div class="tsk">
            <a href="">{{task.title}} - time:{{task.date}}</a>
            <div class="detail">
                <p>{{task.body}}</p>
                <form action="{% url 'core:change' task.id %}" method="post">
                    {% csrf_token %}
                    {% if view != 'succsess-tasks' and view != 'archived-tasks' %}
                    <button style="background-color: green;" name="action" value="sucsess-!-{{view}}">Sucsess</button>
                    {% endif %}
                    {% if view != 'archived-tasks' %}
                    <button style="background-color: grey;" name="action" value="archive-!-{{view}}">Archive</button>
                    {% endif %}
                    <button style="background-color: red;" name="action" value="delete-!-{{view}}">Delete</button>
                </form>
            </div>
        </div>

    {% empty %}

        <div class="center">
            {% if view == 'main' %}
            <a href="{% url 'core:add-task' %}">No Pending Task avilable add more</a>
            {% else %}
            <a>No {{view}} avilable</a>
            {% endif %}
        </div>

    {% endfor %}

</body>
</html>

custom/templates/html/login.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>login</title>

        <style>
            body {
                background-color: blanchedalmond;
            }
            a{
                font-size: 16px;
                color: black;
                font-weight: bolder;
                text-decoration: none;
            }
            .custom_form{
                left      : 50%;
                top       : 50%;
                position  : absolute;
                transform : translate(-50%, -50%);
                text-align: center;
                background-color: pink;
                min-height: 20%;
                min-width: 20%;
                padding: 10px;
            }
            .error {
                text-align: center;
                font-size: large;
                font-weight: bold;
                color: red;
            }
            form {
                margin: 20px;
            }
        </style>

    </head>

    <body>
        <div class="custom_form styling">
            <h2>Sign In</h2>
            {% if messages %}
                {% for message in messages %}
                <p class="error" >{{ message }}</p>
                {% endfor %}
            {% endif %}
            <form action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                <input type="text" name="username" id="name" placeholder="username"><br><br>
                <input type="password" name="password" id="pass" placeholder="password"><br><br>
                <input type="submit">
            </form>
            <a href="{% url 'auth:signup' %}">Sign UP</a>
        </div>
    </body>

</html>

custom/templates/html/sigup.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>login</title>

        <style>
            body {
                background-color: blanchedalmond;
            }
            a{
                font-size: 16px;
                color: black;
                font-weight: bolder;
                text-decoration: none;
            }
            .custom_form{
                left      : 50%;
                top       : 50%;
                position  : absolute;
                transform : translate(-50%, -50%);
                text-align: center;
                background-color: pink;
                min-height: 20%;
                min-width: 20%;
                padding: 10px;
            }
            .error {
                text-align: center;
                font-size: large;
                font-weight: bold;
                color: red;
            }
            form {
                margin: 20px;
            }
        </style>

    </head>

    <body>
        <div class="custom_form styling">
            <h2>Sign Up</h2>
            {% if messages %}
                {% for message in messages %}
                <p class="error" >{{ message }}</p>
                {% endfor %}
            {% endif %}
            <form action="{% url 'auth:signup' %}" method="post">
                {% csrf_token %}
                <input type="text" name="username" id="name" placeholder="username"><br><br>
                <input type="password" name="password" id="pass" placeholder="password"><br><br>
                <input type="submit">
            </form>
            <a href="{% url 'auth:login' %}">Sign In</a>
        </div>
    </body>

</html>